version: "3.4"

services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tipapp
    expose:
      - 5432
    ports:
      - 5432:5432
    command: "-p 5432"